name: Release

on:
  push:
    branches:
      - feat/vpugithubactions

jobs:
  release:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version-file: go.mod

      - name: Tidy go.mod
        run: go mod tidy

      - name: Release with Goreleaser
        uses: goreleaser/goreleaser-action@v6.3.0
        with:
          version: v2.8.2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}